// <auto-generated />
namespace BonoLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deployrol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deployrol));
        
        string IMigrationMetadata.Id
        {
            get { return "202007011853283_deployrol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
